[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graphml"
version = "0.1.0"
description = "My package description"
readme = "README.rst"
requires-python = ">=3.11"
